version: '3.7'

services:

  backendtest:
    container_name: BackendTest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --root-path /api/v1
    ports:
      - 4445:8080