name: "CI CD actions"
on:
  push:
    tags:
      - 'v*'
    branches:
      - Test
      - Prod
  pull_request:
    branches:
      - Test
      - Prod
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Test with unittest module
      run: python -m unittest discover -v -s ./src
  sonarcloud:
    name: SonarCloud code analyze
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.result == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox -e py
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  lint:
    name: Code style check
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.result == 'success' && github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - uses: TrueBrain/actions-flake8@v2
        with:
          only_warn: 1
          max_line_length: 80
          extra_arguments: "--max-complexity=10"
  test_deploy:
    name: Test deploy
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.result == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/Test'
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            cd ${{ secrets.PROJECT_FOLDER }};
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S git checkout Test;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S git pull;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker-compose --file docker-compose.yml down;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker-compose --file docker-compose.yml up -d --build;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker system prune --all --force;
  prod_deploy:
    name: Prod deploy
    runs-on: ubuntu-latest
    needs: test
    if: |
      needs.test.result == 'success' && 
      github.event_name == 'push' && 
      github.ref_type == 'tag' &&
      git branch -r --contains tags/${{ github.ref_name }} | grep -qw 'origin/Prod'
    steps:
    - name: Echo tag
      run: echo ${{ github.ref_name }}
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            cd ${{ secrets.PROJECT_FOLDER }};
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S git checkout Prod;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S git pull;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker-compose --file docker-compose.prod.yml down;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker-compose --file docker-compose.prod.yml up -d --build;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker system prune --all --force;
  sphinx_docs_to_gh-pages:
    permissions:
      contents: write
      pages: write
    name: Docs deploy
    runs-on: ubuntu-latest
    needs: prod_deploy
    if: needs.prod_deploy.result == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install -r docs/requirements.txt
      - name: Build docs
        run: |
          sphinx-apidoc -o docs .
          cd docs
          make html
      - name: Deploy docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          cname: ${{ secrets.DOCS_PAGES_DOMAIN }}
