name: Lint
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  lint:
    name: Flake8 with annotations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - uses: TrueBrain/actions-flake8@v2
        with:
          only_warn: 1
          max_line_length: 80
          extra_arguments: "--max-complexity=10"
