name: "OMMAT CiCd Test"
on:
  push:
    branches:
      - Test
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest module
      run: |
        python3 -m unittest
  deploy:
    name: Deploy Backend Test
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            cd ${{ secrets.PROJECT_FOLDER }};
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S git checkout Test;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S git pull;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker-compose --file docker-compose.yml down;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker-compose --file docker-compose.yml up -d --build;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker system prune --all --force;
