# This workflow will install Python dependencies, run tests with a variety of Python versions

name: Test
on:
  push:
    branches:
      - Prod
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest module
      run: |
        if [ -f test_runner.py ]; then python3 -m unittest test_runner.py; else python3 -m unittest; fi
